kind: Deployment
apiVersion: apps/v1
metadata:
  name: pokedex-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokedex-react
  template:
    metadata:
      labels:
        app: pokedex-react
    spec:
      containers:
        - name: pokedex-react
          image: localhost:5000/pokedex-react
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: pokedex-react
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: pokedex-react